### ISSUE TITLE
Diff with Neogit

### ISSUE THREAD

**Issue by LeiTi34** [daschw/leaf.nvim#1]
Hi, I have a problem with Neogit. When a diff is selected, the background and foreground color of the text are the same.

![image](https://user-images.githubusercontent.com/12941627/163674107-e44ac8fc-a1f0-4c7c-85c2-72a28991829b.png)

When it isn't selected it works fine.

![image](https://user-images.githubusercontent.com/12941627/163674132-43b8d3bc-8fc1-481d-b83f-0b342965b2e1.png)

You can find my configs [here](https://github.com/LeiTi34/.dotfiles/tree/master/nvim/.config/nvim). I really like your theme, keep up the good work.

**Comment by daschw** [comment]
Hi, thanks for reporting and your kind words! I hope I fixed this with https://github.com/daschw/leaf.nvim/commit/1d1e2eaffc42dee59d0dbef1c8c56648161eebc8. Could you give it a try and let me know?

**Comment by LeiTi34** [comment]
Works great now! ty
