### ISSUE TITLE
Move images in ./assets folder to issues

### ISSUE THREAD

**Issue by younger-1** [daschw/leaf.nvim#2]
This can reduce the repo size significantly!

**Comment by daschw** [comment]
Oh yeah, thanks for the hint! I'll use this issue for the images
![preview](https://user-images.githubusercontent.com/16589944/166641976-daa81242-d2b4-4de0-bdce-f0e69253cd71.png)
![screenshot-light](https://user-images.githubusercontent.com/16589944/166642237-0a5bfa8c-e0e9-43b7-bd22-4117a2e25e07.png)
![screenshot-lighter](https://user-images.githubusercontent.com/16589944/166642333-7445b8cc-9be9-4266-bc58-83cae6b3b5a5.png)
![screenshot-lightest](https://user-images.githubusercontent.com/16589944/166642371-a2306844-2c4a-4089-9c11-c1a0413d7157.png)
![screenshot-dark](https://user-images.githubusercontent.com/16589944/166642487-7a8f37d7-3db5-4296-90ed-0413dbcd596b.png)
![screenshot-darker](https://user-images.githubusercontent.com/16589944/166642507-2f50a997-9b35-481b-95f1-88c3dd5a3876.png)
![screenshot-darkest](https://user-images.githubusercontent.com/16589944/166642518-074d2dbf-5ea4-4c99-a0d8-847a36780952.png)
