### ISSUE TITLE
Still getting undercurls with `undercurl = false`

### ISSUE THREAD

**Issue by heygarrett** [daschw/leaf.nvim#3]
Not sure what I might be doing wrong.

<img width="339" alt="Screen Shot 2022-07-04 at 01 07 06" src="https://user-images.githubusercontent.com/1154912/177085208-63b8defb-320f-4506-a20a-ccbe47ec7545.png">

Do I need to change something in the diagnostics settings? I haven't explored them much, so I'm not super familiar.

**Comment by daschw** [comment]
Hi, thanks a lot for reporting! I hope I fixed it in https://github.com/daschw/leaf.nvim/commit/0616e5634a990726a2f9ed8f473317c872abe566.

**Comment by heygarrett** [comment]
Yep! Thank you so much. And looking at your changes helped me figure out how to configure underlines in my diagnostics config as well, so thank you for that too. 😊
