### ISSUE TITLE
feature request: change theme between light and dark based on background

### ISSUE THREAD

**Issue by jan-xyz** [daschw/leaf.nvim#7]
It would be nice if the theme automatically switched between light and dark based on the background state.

```vim
:set background=dark
:set background=light
```

themes like [vim-one](https://github.com/rakr/vim-one) do it like that and it's much simpler to switch between light and dark this way

**Comment by daschw** [comment]
Thanks for the suggestion! Instead of
```lua
require("leaf").setup({
    ...
    theme = "light", -- default, alternatives: "dark", "lighter", "darker", "lightest", "darkest"
})
```
you can now use
```lua
require("leaf").setup({
    ...
    theme = "auto", -- default, based on vim.o.background, alternatives: "light", "dark"
    contrast = "low", -- default, alternatives: "medium", "high"
})
```
With `theme = "auto"` you can switch between dark and light with `:set background=...`.

**Comment by jan-xyz** [comment]
Thank you! That was very fast 😊
